**TEMP** add fake build step

diff --git a/.github/workflows/actions/deploy-environment/action.yml b/.github/workflows/actions/deploy-environment/action.yml
--- a/.github/workflows/actions/deploy-environment/action.yml
+++ b/.github/workflows/actions/deploy-environment/action.yml
@@ -20,68 +20,73 @@ inputs:
 outputs:
   environment_url:
     description: 'The base URL for the deployed environment'
-    value: ${{ steps.terraform.outputs.url }}
+    value: ${{ steps.dummy.outputs.url }}
 
 runs:
   using: composite
 
   steps:
-    - name: Extract configuration from tfvars
-      id: config
-      run: |
-        RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)
-        STORAGE_ACCOUNT_NAME=$(jq -r '.storage_account_name' $TFVARS)
-
-        if [ -z "$RESOURCE_GROUP_NAME" ]; then
-          echo "::error ::Failed to extract resource_group_name from $TFVARS"
-          exit 1
-        fi
-
-        if [ -z "$STORAGE_ACCOUNT_NAME" ]; then
-          echo "::error ::Failed to extract storage_account_name from $TFVARS"
-          exit 1
-        fi
-
-        echo "resource_group_name=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
-        echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
-      shell: bash
-      env:
-        TFVARS: ${{ inputs.terraform_vars }}
-      working-directory: terraform
-
-    - name: Extract version
-      id: get_version
-      run: |
-        API_VERSION=${DOCKER_IMAGE##*:}
-        echo "api_version=$API_VERSION" >> $GITHUB_ENV
-      env:
-        DOCKER_IMAGE: ${{ inputs.docker_image }}
-      shell: bash
-
-    - uses: Azure/login@v1
-      with:
-        creds: ${{ inputs.azure_credentials }}
-
     - run: |
-        TFSTATE_CONTAINER_ACCESS_KEY="$(az storage account keys list -g ${{ env.resource_group_name }} -n ${{ env.storage_account_name }} | jq -r '.[0].value')"
-        echo "::add-mask::$TFSTATE_CONTAINER_ACCESS_KEY"
-        echo "TFSTATE_CONTAINER_ACCESS_KEY=$TFSTATE_CONTAINER_ACCESS_KEY" >> $GITHUB_ENV
-      shell: bash
+        echo fake build....
+        echo "url=http://${{github.event.inputs.environment_name}}-url" >> $GITHUB_ENV
+        sleep 60
+      id: dummy
+    # - name: Extract configuration from tfvars
+    #   id: config
+    #   run: |
+    #     RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)
+    #     STORAGE_ACCOUNT_NAME=$(jq -r '.storage_account_name' $TFVARS)
 
-    - uses: hashicorp/setup-terraform@v1
-      with:
-        terraform_version: 1.0.10
-        terraform_wrapper: false
+    #     if [ -z "$RESOURCE_GROUP_NAME" ]; then
+    #       echo "::error ::Failed to extract resource_group_name from $TFVARS"
+    #       exit 1
+    #     fi
 
-    - name: Terraform
-      id: terraform
-      run: |
-        make ci ${{ inputs.environment_name }} terraform-apply
-        cd terraform
-        echo "url=https://$(terraform output -raw api_fqdn)/" >> $GITHUB_OUTPUT
-      env:
-        ARM_ACCESS_KEY: ${{ env.TFSTATE_CONTAINER_ACCESS_KEY }}
-        TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
-        TF_VAR_api_docker_image: ${{ inputs.api_docker_image }}
-        TF_VAR_api_app_version: ${{ env.api_version }}
-      shell: bash
+    #     if [ -z "$STORAGE_ACCOUNT_NAME" ]; then
+    #       echo "::error ::Failed to extract storage_account_name from $TFVARS"
+    #       exit 1
+    #     fi
+
+    #     echo "resource_group_name=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
+    #     echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
+    #   shell: bash
+    #   env:
+    #     TFVARS: ${{ inputs.terraform_vars }}
+    #   working-directory: terraform
+
+    # - name: Extract version
+    #   id: get_version
+    #   run: |
+    #     API_VERSION=${DOCKER_IMAGE##*:}
+    #     echo "api_version=$API_VERSION" >> $GITHUB_ENV
+    #   env:
+    #     DOCKER_IMAGE: ${{ inputs.docker_image }}
+    #   shell: bash
+
+    # - uses: Azure/login@v1
+    #   with:
+    #     creds: ${{ inputs.azure_credentials }}
+
+    # - run: |
+    #     TFSTATE_CONTAINER_ACCESS_KEY="$(az storage account keys list -g ${{ env.resource_group_name }} -n ${{ env.storage_account_name }} | jq -r '.[0].value')"
+    #     echo "::add-mask::$TFSTATE_CONTAINER_ACCESS_KEY"
+    #     echo "TFSTATE_CONTAINER_ACCESS_KEY=$TFSTATE_CONTAINER_ACCESS_KEY" >> $GITHUB_ENV
+    #   shell: bash
+
+    # - uses: hashicorp/setup-terraform@v1
+    #   with:
+    #     terraform_version: 1.0.10
+    #     terraform_wrapper: false
+
+    # - name: Terraform
+    #   id: terraform
+    #   run: |
+    #     make ci ${{ inputs.environment_name }} terraform-apply
+    #     cd terraform
+    #     echo "url=https://$(terraform output -raw api_fqdn)/" >> $GITHUB_OUTPUT
+    #   env:
+    #     ARM_ACCESS_KEY: ${{ env.TFSTATE_CONTAINER_ACCESS_KEY }}
+    #     TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
+    #     TF_VAR_api_docker_image: ${{ inputs.api_docker_image }}
+    #     TF_VAR_api_app_version: ${{ env.api_version }}
+    #   shell: bash
