Update KeyVault & storage refs in make & tf files
To align the workflows and resources with the current standards the
references in the make and terraform files to Azure storage and KeyVault
resources have been updated.

diff --git a/.github/workflows/actions/deploy-environment/action.yml b/.github/workflows/actions/deploy-environment/action.yml
--- a/.github/workflows/actions/deploy-environment/action.yml
+++ b/.github/workflows/actions/deploy-environment/action.yml
@@ -36,6 +36,8 @@ runs:
       run: |
         KEY_VAULT_NAME=$(jq -r '.key_vault_name' $TFVARS)
         PAAS_SPACE=$(jq -r '.paas_space' $TFVARS)
+        RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)
+        STORAGE_ACCOUNT_NAME=$(jq -r '.storage_account_name' $TFVARS)
 
         if [ -z "$KEY_VAULT_NAME" ]; then
           echo "::error ::Failed to extract key_vault_name from $TFVARS"
@@ -47,8 +49,20 @@ runs:
           exit 1
         fi
 
+        if [ -z "$RESOURCE_GROUP_NAME" ]; then
+          echo "::error ::Failed to extract resource_group_name from $TFVARS"
+          exit 1
+        fi
+
+        if [ -z "$STORAGE_ACCOUNT_NAME" ]; then
+          echo "::error ::Failed to extract storage_account_name from $TFVARS"
+          exit 1
+        fi
+
         echo ::set-output name=key_vault_name::$KEY_VAULT_NAME
         echo ::set-output name=paas_space::$PAAS_SPACE
+        echo "resource_group_name=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
+        echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
       shell: bash
       env:
         TFVARS: ${{ inputs.terraform_vars }}
@@ -67,11 +81,18 @@ runs:
       with:
         creds: ${{ inputs.azure_credentials }}
 
+    # get TFSTATE-CONTAINER-ACCESS-KEY
+    - run: |
+        TFSTATE_CONTAINER_ACCESS_KEY="$(az storage account keys list -g ${{ env.resource_group_name }} -n ${{ env.storage_account_name }} | jq -r '.[0].value')"
+        echo "::add-mask::$TFSTATE_CONTAINER_ACCESS_KEY"
+        echo "TFSTATE_CONTAINER_ACCESS_KEY=$TFSTATE_CONTAINER_ACCESS_KEY" >> $GITHUB_ENV
+      shell: bash
+
     - uses: Azure/get-keyvault-secrets@v1
       id: get_secrets
       with:
         keyvault: ${{ steps.config.outputs.key_vault_name }}
-        secrets: 'TFSTATE-CONTAINER-ACCESS-KEY,TEST-API-KEY,PAAS-USER,PAAS-PASSWORD'
+        secrets: 'TEST-API-KEY,PAAS-USER,PAAS-PASSWORD'
 
     - uses: hashicorp/setup-terraform@v1
       with:
@@ -102,7 +123,7 @@ runs:
         make ci ${{ inputs.environment_name }} terraform-apply
         cd terraform && echo ::set-output name=url::https://$(terraform output -raw api_fqdn)/
       env:
-        ARM_ACCESS_KEY: ${{ steps.get_secrets.outputs.TFSTATE-CONTAINER-ACCESS-KEY }}
+        ARM_ACCESS_KEY: ${{ env.TFSTATE_CONTAINER_ACCESS_KEY }}
         TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
         TF_VAR_api_docker_image: ${{ inputs.docker_image }}
         TF_VAR_api_app_version: ${{ steps.get_version.outputs.api_version }}
